version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: discord-bot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: discord
      POSTGRES_USER: discord
      POSTGRES_PASSWORD: discord
    ports:
      - '5437:5432'
